### ISSUE TITLE
Multiple floors?

### ISSUE THREAD

**Issue by RayBytes** [kno20205/pathpal-indoor-navigation#5]
Im assuming the current implementation does not have the ability to work accross multiply floors. Could you suggest exactly how would one change the current code to accomplish that? Im willing to code it but would like some guidance as to how the implementation of that would work.

**Comment by KnotzerIO** [comment]
This project is just a simple prototype, so I didn't include multi-floor functionality to keep things straightforward. Adding that feature would require significant effort, and I chose to focus on the basics. However, if you want to implement it, you can make it work across multiple floors by assigning a floor ID to each location and creating separate map layers for each floor.The routing algorithm would need to account for stairs or elevators, linking different floors. You could start with a simple floor selection dropdown or add automatic floor detection later if needed. In the future, I’m planning a larger project with more features, including a map editor and additional functionality.
