### ISSUE TITLE
How to do build?

### ISSUE THREAD

**Issue by demirmehmet0** [kno20205/pathpal-indoor-navigation#6]
How can I build this React application to add it to my own web application? When I use the js and css files from npm run build, only the toastmessage div is added to the div with the root id and nothing else is added.

**Comment by KnotzerIO** [comment]
Is your code open? If Yes I can take a look. Also have you considered using an iframe to embed it in your app?

**Comment by KnotzerIO** [comment]
Closed this issue due to inactivity from the original requester.
